version: '3.9'

services:
  touitomamout:
    container_name: "touitomamout"
    build:
      context: ./  # ← This will build the image from the source code
    restart: unless-stopped
    environment:
      - ENV_FILE=/data/.env
      - STORAGE_DIR=/data
    volumes:
      - ./data:/data
