name: GitHub Release

on:
  workflow_dispatch

jobs:
  create-tag:
    name: "Create tag from package.json"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.create-tag.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Git tag
        id: create-tag
        run: |
          version="v$(jq -r '.version' package.json)"
          git tag $version
          git push origin $version
          echo "version=$version" >> "$GITHUB_OUTPUT"


  github-release:
    needs:
      - create-tag
    name: "Create GitHub release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create changelog
        id: changelog
        uses: loopwerk/tag-changelog@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/tag-changelog.cjs

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.create-tag.outputs.version}}
          release_name: Release ${{needs.create-tag.outputs.version}}
          body: ${{ steps.changelog.outputs.changes }}
